---

name: "Deployment of all OS packages to the own repo server"

################################################################################
# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      repo_server:
        description: 'The hostname name of the repository server.'
        required: true
      repo_user:
        description: 'The name of the user on the receiving repository server.'
        required: true
      ssh_private_key:
        description: 'The private SSH key of the user on the receiving repository server.'
        required: true
      repo_dir:
        description: 'The parent input directory on the receiving repository server.'
        required: true

################################################################################
defaults:
  run:
    shell: bash

################################################################################
jobs:

  ###########################
  deploy_to_repo:
    runs-on: ubuntu-latest
    name: "Deployment of all Packages to Frank Brehms repo server"
    if: ${{ github.ref_type == 'tag' || github.ref_name == 'dev/workflow' }}
    steps:

      - name: "Checking out sources."
        uses: actions/checkout@v4

      - name: "Downloading all artifacts."
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: "Got current stuff."
        run: |
          echo -e "\nAll current artifacts:"
          find artifacts -print0 | xargs --null --no-run-if-empty ls -l -d --color=always

      - name: 'Sorting all artifacts'
        shell: bash
        run: |
          mv -vi artifacts/debian_bin_pkgs_*/* artifacts/
          mv -vi artifacts/debian_sources/src artifacts/
          rmdir -v artifacts/debian_bin_pkgs_* artifacts/debian_sources
          for el_version in 7 8 9 10 ; do
            if [[ -d artifacts/rpm_pkgs_el${el_version} ]]; then
              mkdir -pv artifacts/el-${el_version}
              mv -vi artifacts/rpm_pkgs_el${el_version}/*/*/*.rpm artifacts/rpm_pkgs_el${el_version}/*/*.rpm artifacts/el-${el_version}/
            fi
          done
          rm -rv artifacts/rpm_pkgs_el*

          echo -e "\nAll sorted artifacts:"
          find artifacts -print0 | xargs --null --no-run-if-empty ls -l -d --color=always

      - name: 'Install private SSH Key'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ssh_private_key }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: 'Adding Known Hosts'
        run: |
          ssh-keyscan -H ${{ secrets.repo_server }} >> ~/.ssh/known_hosts

      - name: 'Show .ssh dir'
        run: |
          echo -e "\nDirectory ~/.ssh/:"
          ls -l --color=always ~/.ssh/

          echo -e "\nContent of ~/.ssh/known_hosts:"
          cat ~/.ssh/known_hosts
          echo "<--"

      - name: 'Deploy Python packages'
        run: |

          target="${{ secrets.repo_dir}}/python"
          # echo -e "\nEnsuring target directory '${target}' ..."
          # if ssh ${{ secrets.repo_user }}@${{ secrets.repo_server }} 'test -d ${target}' ; then
          #     echo ' * already exists.'
          # else
          #     echo ' * Creating.'
          #     ssh ${{ secrets.repo_user }}@${{ secrets.repo_server }} 'mkdir -p -v ${target}'
          # fi

          cmd="rsync -aHvz artifacts/python_pkgs/ ${{ secrets.repo_user }}@${{ secrets.repo_server }}:${{ secrets.repo_dir }}${target}/"
          echo -e "\nExecuting: ${cmd}"
          eval ${cmd}

      - name: 'Deploy Debian packages with rsync'
        run: |

          cmd="rsync -aHvz artifacts/deb* artifacts/ubuntu* artifacts/src"
          cmd+=" ${{ secrets.repo_user }}@${{ secrets.repo_server }}:${{ secrets.repo_dir}}/debian/"

          echo -e "\nExecuting: ${cmd}"
          eval ${cmd}

      - name: 'Deploy RPM packages with rsync'
        run: |

          cmd="rsync -aHvz artifacts/el-* ${{ secrets.repo_user }}@${{ secrets.repo_server }}:${{ secrets.repo_dir }}/el/"

          echo -e "\nExecuting: ${cmd}"
          eval ${cmd}


# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
